# Generated by Django 5.2.7 on 2025-11-02 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('coding', 'Coding Question')], default='multiple_choice', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.TextField(blank=True, help_text='Expected solution code'),
        ),
        migrations.AddField(
            model_name='question',
            name='starter_code',
            field=models.TextField(blank=True, help_text='Initial code template for coding questions'),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text='Input as JSON string')),
                ('expected_output', models.TextField(help_text='Expected output as JSON string')),
                ('is_hidden', models.BooleanField(default=False, help_text='Hide test case from user')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='quiz.question')),
            ],
        ),
    ]
